export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM='DELETE_ITEM';
export const VISIBLE_SEARCH='VISIBLE_SERACH';
export const CHANGE_ITEMDONE='CHANGE_ITEMDONE';
export const VISIBLE_ALLDONE='VISIBLE_ALLDONE';
export const VISIBLE_DONE='VISIBLE_DONE';
export const VISIBLE_NOTDONE='VISIBLE_NOTDONE';
